package dialogos;

import classes.LivroListener;
import classes.bibliotecaClass;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class addLivroDlg extends javax.swing.JFrame {

    bibliotecaClass bibliotecaClass = new bibliotecaClass();
    private LivroListener listener;
    private String caminhoImagem = "";

    public addLivroDlg() {
        this(null);
    }

    public addLivroDlg(LivroListener listener) {
        this.listener = listener;
        initComponents();
        setTitle("Adicionar Livro");
        setSize(535, 694);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // coisas do campo de descricao
        inputDescricao.setLineWrap(true);
        inputDescricao.setWrapStyleWord(true);
        inputDescricao = new javax.swing.JTextArea();
        inputDescricao.setColumns(20);
        inputDescricao.setRows(5);
        inputDescricao.setLineWrap(true);
        inputDescricao.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        inputNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPaginas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescricao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        addLivroBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("(opcional)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 90, -1));
        getContentPane().add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 230, -1));

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        getContentPane().add(inputAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, -1));

        jLabel3.setText("Ano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));
        getContentPane().add(inputAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, -1));

        jLabel4.setText("Páginas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));
        getContentPane().add(inputPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 110, -1));

        jLabel5.setText("Descrição");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(inputGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, -1));

        inputDescricao.setColumns(20);
        inputDescricao.setRows(5);
        jScrollPane1.setViewportView(inputDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 500, 250));

        jLabel6.setText("Gênero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        addLivroBtn.setText("Adicionar");
        addLivroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLivroBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addLivroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 90, -1));

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("(obrigatorio)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void addLivroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLivroBtnActionPerformed
        String nome = inputNome.getText().trim();
        String autor = inputAutor.getText().trim();
        String anoStr = inputAno.getText().trim();
        String paginasStr = inputPaginas.getText().trim();
        String genero = inputGenero.getText().trim();
        String descricao = inputDescricao.getText().trim();

        // Verificação de campos obrigatórios
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome é obrigatório.", "Erro de validação", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificação de autor e número inteiro positivo para ano e páginas
        int ano, paginas;
        try {
            ano = Integer.parseInt(anoStr);
            paginas = Integer.parseInt(paginasStr);

            if (autor.isEmpty()) {
                autor = "Autor desconhecido"; // se não tiver autor, bota como desconhecido
            }

            if (ano <= 0) {
                anoStr = "Ano desconhecido"; // se não tiver ano, bota como desconhecido
                return;
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ano e Páginas devem ser números inteiros.", "Erro de validação", JOptionPane.ERROR_MESSAGE); // Erro
            return;
        }

        bibliotecaClass.addLivro(nome, autor, ano, paginas, genero, descricao);
        if (listener != null) {
            listener.livroAdicionado(); // Atualiza JTable
        }
        this.dispose();

    }//GEN-LAST:event_addLivroBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLivroDlg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLivroBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField inputAno;
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextArea inputDescricao;
    private javax.swing.JTextField inputGenero;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
