package dialogos;

import classes.LivroListener;
import classes.bibliotecaClass;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import org.json.JSONObject;

public class editLivroDlg extends javax.swing.JFrame {

    bibliotecaClass bibliotecaClass = new bibliotecaClass();
    private LivroListener listener;
    private String caminhoImagem = "";
    private int livroIndex = -1;

    public editLivroDlg() {
        this(null, -1, null);
    }

    public editLivroDlg(JSONObject livro, int index, LivroListener listener) {
        this.listener = listener;
        this.livroIndex = index;
        initComponents();
        setTitle("Editar Livro");
        setSize(535, 694);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Preenche os campos:
        inputNome.setText(livro.optString("nome", ""));
        inputAutor.setText(livro.optString("autor", ""));
        inputAno.setText(String.valueOf(livro.optInt("ano", 0)));
        inputPaginas.setText(String.valueOf(livro.optInt("paginas", 0)));
        inputGenero.setText(livro.optString("genero", ""));
        inputDescricao.setText(livro.optString("descricao", ""));
        caminhoImagem = livro.optString("imagem", "");

        // Carrega imagem:
        if (!caminhoImagem.isEmpty()) {
            ImageIcon icon = new ImageIcon(new ImageIcon(caminhoImagem)
                    .getImage().getScaledInstance(260, 230, java.awt.Image.SCALE_SMOOTH));
            JLabel imgLabel = new JLabel(icon);
            livroImgPanel.removeAll();
            livroImgPanel.add(imgLabel);
            livroImgPanel.revalidate();
            livroImgPanel.repaint();
        }

        livroImgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarImagem();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        inputNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPaginas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescricao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        addLivroEditadoBtn = new javax.swing.JButton();
        livroImgPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 90, -1));
        getContentPane().add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 230, -1));

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        getContentPane().add(inputAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, -1));

        jLabel3.setText("Ano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));
        getContentPane().add(inputAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, -1));

        jLabel4.setText("Páginas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));
        getContentPane().add(inputPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 110, -1));

        jLabel5.setText("Descrição");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(inputGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, -1));

        inputDescricao.setColumns(20);
        inputDescricao.setRows(5);
        jScrollPane1.setViewportView(inputDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 500, 250));

        jLabel6.setText("Gênero");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        addLivroEditadoBtn.setText("Salvar Edição");
        addLivroEditadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLivroEditadoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addLivroEditadoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 90, -1));

        jLabel7.setText("Imagem");
        livroImgPanel.add(jLabel7);

        getContentPane().add(livroImgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void addLivroEditadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLivroEditadoBtnActionPerformed
        String nome = inputNome.getText();
        String autor = inputAutor.getText();
        int ano = Integer.parseInt(inputAno.getText());
        int paginas = Integer.parseInt(inputPaginas.getText());
        String genero = inputGenero.getText();
        String descricao = inputDescricao.getText();
        bibliotecaClass.atualizarLivro(livroIndex, nome, autor, ano, paginas, genero, descricao, caminhoImagem);
        if (listener != null) {
            listener.livroAdicionado(); // chama o mainBiblioteca para atualizar JTable
        }
        this.dispose();
    }//GEN-LAST:event_addLivroEditadoBtnActionPerformed

    private void selecionarImagem() {
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            caminhoImagem = chooser.getSelectedFile().getAbsolutePath();
            // Exibe miniatura da imagem no painel (opcional)
            livroImgPanel.removeAll();
            JLabel imgLabel = new JLabel(new ImageIcon(new ImageIcon(caminhoImagem).getImage().getScaledInstance(260, 230, java.awt.Image.SCALE_SMOOTH)));
            livroImgPanel.add(imgLabel);
            livroImgPanel.revalidate();
            livroImgPanel.repaint();
        }
    }

    public void setLivroParaEdicao(JSONObject livro, int index) {
        this.livroIndex = index;

        inputNome.setText(livro.optString("nome", ""));
        inputAutor.setText(livro.optString("autor", ""));
        inputAno.setText(String.valueOf(livro.optInt("ano", 0)));
        inputPaginas.setText(String.valueOf(livro.optInt("paginas", 0)));
        inputGenero.setText(livro.optString("genero", ""));
        inputDescricao.setText(livro.optString("descricao", ""));
        caminhoImagem = livro.optString("imagem", "");

        if (!caminhoImagem.isEmpty()) {
            ImageIcon icon = new ImageIcon(new ImageIcon(caminhoImagem)
                    .getImage().getScaledInstance(260, 230, java.awt.Image.SCALE_SMOOTH));
            JLabel imgLabel = new JLabel(icon);
            livroImgPanel.removeAll();
            livroImgPanel.add(imgLabel);
            livroImgPanel.revalidate();
            livroImgPanel.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editLivroDlg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLivroEditadoBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField inputAno;
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextArea inputDescricao;
    private javax.swing.JTextField inputGenero;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel livroImgPanel;
    // End of variables declaration//GEN-END:variables
}
