package telas;

import dialogos.addCronometroLivreDlg;
import dialogos.addPomodoroDlg;
import dialogos.addTemporizadorDlg;
import javax.swing.JFrame;
import javax.swing.JTextArea;

public class mainTimer extends javax.swing.JFrame {

    JTextArea descricaoArea;

    public mainTimer() {
        initComponents();
        setTitle("Timer");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        painelLateral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        buttonList = new javax.swing.JTable();
        painelCentral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        addTimerMenuBtn = new javax.swing.JMenu();
        novoPomodoroMenuBtn = new javax.swing.JMenuItem();
        cronLivreMenuBtn = new javax.swing.JMenuItem();
        temporizadorMenuBtn = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(buttonList);

        javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
        painelLateral.setLayout(painelLateralLayout);
        painelLateralLayout.setHorizontalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelLateralLayout.setVerticalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(painelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 780));

        painelCentral.setLayout(new javax.swing.BoxLayout(painelCentral, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(painelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 880, 520));

        addTimerMenuBtn.setText("Timer");
        addTimerMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTimerMenuBtnActionPerformed(evt);
            }
        });

        novoPomodoroMenuBtn.setText("Novo Pomodoro");
        novoPomodoroMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPomodoroMenuBtnActionPerformed(evt);
            }
        });
        addTimerMenuBtn.add(novoPomodoroMenuBtn);

        cronLivreMenuBtn.setText("Cronômetro Livre");
        cronLivreMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cronLivreMenuBtnActionPerformed(evt);
            }
        });
        addTimerMenuBtn.add(cronLivreMenuBtn);

        temporizadorMenuBtn.setText("Temporizador");
        temporizadorMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temporizadorMenuBtnActionPerformed(evt);
            }
        });
        addTimerMenuBtn.add(temporizadorMenuBtn);

        jMenuBar1.add(addTimerMenuBtn);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTimerMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTimerMenuBtnActionPerformed
        
    }//GEN-LAST:event_addTimerMenuBtnActionPerformed

    private void novoPomodoroMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPomodoroMenuBtnActionPerformed
        addPomodoroDlg pomodoroDlg = new addPomodoroDlg();
        pomodoroDlg.setVisible(true);
    }//GEN-LAST:event_novoPomodoroMenuBtnActionPerformed

    private void cronLivreMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cronLivreMenuBtnActionPerformed
        addCronometroLivreDlg cronLivreDlg = new addCronometroLivreDlg();
        cronLivreDlg.setVisible(true);
    }//GEN-LAST:event_cronLivreMenuBtnActionPerformed

    private void temporizadorMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temporizadorMenuBtnActionPerformed
        addTemporizadorDlg temporizadorDlg = new addTemporizadorDlg();
        temporizadorDlg.setVisible(true);
    }//GEN-LAST:event_temporizadorMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addTimerMenuBtn;
    private javax.swing.JTable buttonList;
    private javax.swing.JMenuItem cronLivreMenuBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem novoPomodoroMenuBtn;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelLateral;
    private javax.swing.JMenuItem temporizadorMenuBtn;
    // End of variables declaration//GEN-END:variables
}
