package com.mycompany.estudex;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import org.json.JSONArray;
import org.json.JSONObject;
import biblioteca.mainBiblioteca;
import telas.mainDocumento;
import telas.mainNotas;
import dialogos.dlgSobre;
import telas.mainTarefas;
import timer.mainTimer;

public class index extends javax.swing.JFrame {

    public index() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(1050, 690);
        setVisible(true);
        setLocationRelativeTo(null);

        JLabel fraseLabel = new JLabel(formatarFrase(mostrarFraseMotivacionalQueVaiFazerOCaraVirarODavidGoggins()), SwingConstants.CENTER);
        fraseLabel.setFont(new Font("Serif", Font.PLAIN, 16));
        fraseLabel.setForeground(new Color(255, 255, 255));

        // Define um layout que aceita centralização
        frasePanel.setLayout(new BorderLayout());
        frasePanel.add(fraseLabel, BorderLayout.CENTER);
        
        //icones do botão
        // slk agradecimentos ao flarom (ta nos contribuidores do projeto)
        // por ter me ajudado com essa técnica milenar 
        
        homeBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24));
        homeBtn.setText("\ue80f");
        
        bibliotecaBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24));
        bibliotecaBtn.setText("\ue8f1");
        
        timerBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24)); // NOI18N
        timerBtn.setText("\ue823");
        
        documentsBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24)); // NOI18N
        documentsBtn.setText("\ue7c3");
        
        tarefasBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24)); // NOI18N
        tarefasBtn.setText("\ue71d");
        
        notasBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24)); // NOI18N
        notasBtn.setText("\ue70b");
        
        sobreBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 24)); // NOI18N
        sobreBtn.setText("\ue946");
    }

    private JSONObject mostrarFraseMotivacionalQueVaiFazerOCaraVirarODavidGoggins() {
        try {
            String jsonText = Files.readString(Path.of("data/frases.json"));
            JSONObject jsonObj = new JSONObject(jsonText);
            JSONArray frases = jsonObj.getJSONArray("frases");

            int indice = new Random().nextInt(frases.length());
            return frases.getJSONObject(indice);

        } catch (IOException e) {
            e.printStackTrace();
            return new JSONObject()
                    .put("texto", "Erro ao carregar frases.")
                    .put("autor", "Sistema");
        }
    }

    private String formatarFrase(JSONObject fraseObj) {
        String texto = fraseObj.getString("texto");
        String autor = fraseObj.getString("autor");
        return "<html><div style='text-align:center'>“" + texto + "”<br><br><i>— " + autor + "</i></div></html>";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frasePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        documentsBtn = new javax.swing.JButton();
        tarefasBtn = new javax.swing.JButton();
        notasBtn = new javax.swing.JButton();
        bibliotecaBtn = new javax.swing.JButton();
        timerBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        sobreBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(48, 52, 63));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frasePanel.setBackground(new java.awt.Color(54, 56, 58));

        javax.swing.GroupLayout frasePanelLayout = new javax.swing.GroupLayout(frasePanel);
        frasePanel.setLayout(frasePanelLayout);
        frasePanelLayout.setHorizontalGroup(
            frasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        frasePanelLayout.setVerticalGroup(
            frasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(frasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 960, 210));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        documentsBtn.setBackground(new java.awt.Color(60, 63, 65));
        documentsBtn.setBorder(null);
        documentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(documentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        tarefasBtn.setBackground(new java.awt.Color(60, 63, 65));
        tarefasBtn.setBorder(null);
        tarefasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tarefasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        notasBtn.setBackground(new java.awt.Color(60, 63, 65));
        notasBtn.setBorder(null);
        notasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(notasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 50));

        bibliotecaBtn.setBackground(new java.awt.Color(60, 63, 65));
        bibliotecaBtn.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 12)); // NOI18N
        bibliotecaBtn.setBorder(null);
        bibliotecaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bibliotecaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 50));

        timerBtn.setBackground(new java.awt.Color(60, 63, 65));
        timerBtn.setBorder(null);
        timerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(timerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        sobreBtn.setBackground(new java.awt.Color(60, 63, 65));
        sobreBtn.setBorder(null);
        sobreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sobreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem vindo!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 180, 60));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prepare seu material, faça um café e inicie seus estudos !");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 300, -1));

        jPanel2.setBackground(new java.awt.Color(54, 56, 58));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 980, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 
    
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        mainBiblioteca b = new mainBiblioteca();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void bibliotecaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBtnActionPerformed
        mainBiblioteca b = new mainBiblioteca();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bibliotecaBtnActionPerformed

    private void timerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBtnActionPerformed
        mainTimer tim = new mainTimer();
        tim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timerBtnActionPerformed

    private void documentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentsBtnActionPerformed
        mainDocumento d = new mainDocumento();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_documentsBtnActionPerformed

    private void tarefasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefasBtnActionPerformed
        mainTarefas tar = new mainTarefas();
        tar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tarefasBtnActionPerformed

    private void notasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasBtnActionPerformed
        mainNotas n = new mainNotas();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_notasBtnActionPerformed

    private void sobreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreBtnActionPerformed
        dlgSobre s = new dlgSobre();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sobreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao inicializar o FlatLaf");
        }

        SwingUtilities.invokeLater(index::new);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bibliotecaBtn;
    private javax.swing.JButton documentsBtn;
    private javax.swing.JPanel frasePanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton notasBtn;
    private javax.swing.JButton sobreBtn;
    private javax.swing.JButton tarefasBtn;
    private javax.swing.JButton timerBtn;
    // End of variables declaration//GEN-END:variables
}
