package com.mycompany.estudex;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import org.json.JSONArray;
import org.json.JSONObject;

public class index extends javax.swing.JFrame {

    private JLabel fraseLabel;

    public index() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(1050, 650);
        setVisible(true);
        setLocationRelativeTo(null);

        JLabel fraseLabel = new JLabel("<html>“”<br><i>— Autor</i></html>", SwingConstants.CENTER);
        fraseLabel.setFont(new Font("Serif", Font.PLAIN, 16));
        fraseLabel.setForeground(new Color(30, 60, 90));

        // Define um layout que aceita centralização
        frasePanel.setLayout(new BorderLayout());
        frasePanel.add(fraseLabel, BorderLayout.CENTER);

        setVisible(true);
    }

    private JSONObject obterFraseAleatoria() {
        try {
            String jsonText = Files.readString(Path.of("data/frases.json"));
            JSONObject jsonObj = new JSONObject(jsonText);
            JSONArray frases = jsonObj.getJSONArray("frases");

            int indice = new Random().nextInt(frases.length());
            return frases.getJSONObject(indice);

        } catch (IOException e) {
            e.printStackTrace();
            return new JSONObject()
                    .put("texto", "Erro ao carregar frases.")
                    .put("autor", "Sistema");
        }
    }

    private String formatarFrase(JSONObject fraseObj) {
        String texto = fraseObj.getString("texto");
        String autor = fraseObj.getString("autor");

        return "<html><div style='text-align:center'>"
                + "“" + texto + "”<br><br>"
                + "<i>— " + autor + "</i></div></html>";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        frasePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(48, 52, 63));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 122, 33));
        jLabel1.setText("Estudex");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 40));

        jSeparator1.setForeground(new java.awt.Color(105, 122, 33));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 470, 40));

        javax.swing.GroupLayout frasePanelLayout = new javax.swing.GroupLayout(frasePanel);
        frasePanel.setLayout(frasePanelLayout);
        frasePanelLayout.setHorizontalGroup(
            frasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        frasePanelLayout.setVerticalGroup(
            frasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(frasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1030, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarFraseMotivacionalQueVaiFazerOCaraVirarODavidGoggins() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao inicializar o FlatLaf");
        }

        SwingUtilities.invokeLater(index::new);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frasePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
