package com.mycompany.estudex;

import com.formdev.flatlaf.FlatDarkLaf;
import java.nio.file.Files;
import javax.swing.JFrame;
import telas.mainBiblioteca;
import telas.mainCalendario;
import telas.mainNotas;
import telas.mainSobre;
import telas.mainTimer;

public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        setTitle("Estudex");
        setVisible(true);
        setSize(1280 , 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        bibliotecaBtn = new javax.swing.JButton();
        notasBtn = new javax.swing.JButton();
        calendarioBtn = new javax.swing.JButton();
        sobreBtn = new javax.swing.JButton();
        timerBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 174, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 174, 0));
        mainTitle.setText("Estudex");
        getContentPane().add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        bibliotecaBtn.setText("Biblioteca");
        bibliotecaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bibliotecaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 240, 60));

        notasBtn.setText("Notas");
        notasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(notasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 240, 60));

        calendarioBtn.setText("Calendário");
        calendarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calendarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 240, 60));

        sobreBtn.setText("Sobre");
        sobreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sobreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 240, 60));

        timerBtn.setText("Timer");
        timerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(timerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 240, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 174, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 323, 603, 10));

        jLabel1.setText("Estudex é seu app para focar nos estudos, marcar eventos importantes, registrar suas conquistas e sua evolução");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 630, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    mainBiblioteca biblioteca = new mainBiblioteca();
    mainNotas notas = new mainNotas();
    mainTimer timer = new mainTimer();
    mainCalendario calendario = new mainCalendario();
    mainSobre sobre = new mainSobre();
    
    private void bibliotecaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBtnActionPerformed
        new mainBiblioteca();
        biblioteca.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bibliotecaBtnActionPerformed

    private void notasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasBtnActionPerformed
        new mainNotas();
        notas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_notasBtnActionPerformed

    private void calendarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioBtnActionPerformed
        new mainCalendario();
        calendario.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_calendarioBtnActionPerformed

    private void sobreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreBtnActionPerformed
        new mainSobre();
        sobre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sobreBtnActionPerformed

    private void timerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBtnActionPerformed
        new mainTimer();
        timer.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_timerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao inicializar o FlatLaf");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bibliotecaBtn;
    private javax.swing.JButton calendarioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton notasBtn;
    private javax.swing.JButton sobreBtn;
    private javax.swing.JButton timerBtn;
    // End of variables declaration//GEN-END:variables
}
