package com.mycompany.estudex;

import com.formdev.flatlaf.FlatDarkLaf;
import telas.mainBiblioteca;
import telas.mainNotas;
import telas.mainSobre;
import telas.mainTimer;

public class mainIndex extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public mainIndex() {
        initComponents();
        setTitle("Estudex");
        setVisible(true);
        setResizable(false);
        setSize(1280 , 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        bibliotecaBtn = new javax.swing.JButton();
        notasBtn = new javax.swing.JButton();
        tarefasBtn = new javax.swing.JButton();
        timerBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        sobreBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 174, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 174, 0));
        mainTitle.setText("Estudex");
        getContentPane().add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        bibliotecaBtn.setBackground(new java.awt.Color(51, 51, 51));
        bibliotecaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bibliotecaBtn.setForeground(new java.awt.Color(219, 220, 220));
        bibliotecaBtn.setText("Biblioteca");
        bibliotecaBtn.setBorder(null);
        bibliotecaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bibliotecaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 240, 60));

        notasBtn.setBackground(new java.awt.Color(51, 51, 51));
        notasBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notasBtn.setForeground(new java.awt.Color(219, 220, 220));
        notasBtn.setText("Notas");
        notasBtn.setBorder(null);
        notasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(notasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 240, 60));

        tarefasBtn.setBackground(new java.awt.Color(51, 51, 51));
        tarefasBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarefasBtn.setForeground(new java.awt.Color(219, 220, 220));
        tarefasBtn.setText("Tarefas");
        tarefasBtn.setBorder(null);
        tarefasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tarefasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 240, 60));

        timerBtn.setBackground(new java.awt.Color(51, 51, 51));
        timerBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timerBtn.setForeground(new java.awt.Color(219, 220, 220));
        timerBtn.setText("Timer");
        timerBtn.setBorder(null);
        timerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(timerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 240, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 174, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 603, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(219, 220, 220));
        jLabel1.setText("Estudex é seu app para focar nos estudos, marcar eventos importantes, registrar suas conquistas e sua evolução");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 820, 20));

        sobreBtn1.setBackground(new java.awt.Color(51, 51, 51));
        sobreBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sobreBtn1.setForeground(new java.awt.Color(219, 220, 220));
        sobreBtn1.setText("Sobre");
        sobreBtn1.setBorder(null);
        sobreBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(sobreBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 240, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    mainBiblioteca biblioteca = new mainBiblioteca();
    mainNotas notas = new mainNotas();
    mainTimer timer = new mainTimer();
    mainSobre sobre = new mainSobre();
    
    private void bibliotecaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBtnActionPerformed
        new mainBiblioteca();
        biblioteca.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bibliotecaBtnActionPerformed

    private void notasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasBtnActionPerformed
        new mainNotas();
        notas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_notasBtnActionPerformed

    private void tarefasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefasBtnActionPerformed
        
    }//GEN-LAST:event_tarefasBtnActionPerformed

    private void timerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBtnActionPerformed
        new mainTimer();
        timer.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_timerBtnActionPerformed

    private void sobreBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreBtn1ActionPerformed
        new mainSobre();
        sobre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sobreBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao inicializar o FlatLaf");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bibliotecaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton notasBtn;
    private javax.swing.JButton sobreBtn1;
    private javax.swing.JButton tarefasBtn;
    private javax.swing.JButton timerBtn;
    // End of variables declaration//GEN-END:variables
}
